### ISSUE TITLE
CLI npm package should be named "opent2t-cli" instead of "opent2t"

### ISSUE THREAD

**Issue by jasongin** [openT2T/opent2t-cli#1]
`> npm info opent2t`

```
{ name: 'opent2t',
  description: 'Command Line Interface (CLI) for Open Translators to Things.',
  ...
```

The simple "opent2t" name should be reserved for the [OpenT2T core library](https://github.com/opent2t/opent2t) package.

**Comment by tjaffri** [comment]
@jasongin  I made you an owner of this package on npm. Please change as you wish.
